Phase3 KPI Calculation

In [1]:
import pandas as pd

In [2]:
from pathlib import Path
Path.cwd()

WindowsPath('C:/Users/LENOVO/IndiaKart_Project/NoteBooks')

Load Datasets

In [3]:
orders = pd.read_csv("../Cleaned Data/orders_cleaned.csv")

In [4]:
orders.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
0,ORD000001,CUST02946,2025-05-22,17:10:00,Processing,Pune,Maharashtra,300862,100984.19,16364.64,0,20486.45,100984.19,Cash on Delivery,BlueDart,TRK354572763,NaN,1,App
1,ORD000002,CUST04232,2023-10-16,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,2023-10-19,0,Website
2,ORD000003,CUST08078,2023-10-08,12:32:00,Cancelled,Meerut,Uttar Pradesh,294014,32557.06,3562.92,0,696.86,32557.06,Debit Card,Amazon Logistics,TRK338505401,NaN,0,App
3,ORD000004,CUST09612,2023-10-02,08:05:00,Delivered,Nashik,Maharashtra,626047,24836.94,3092.88,0,4029.94,24836.94,UPI,DTDC,TRK289792017,2023-10-09,0,Mobile Web
4,ORD000005,CUST03065,2024-06-15,20:19:00,Delivered,Moradabad,Uttar Pradesh,409210,156689.29,25092.36,0,7805.07,156689.29,UPI,Ecom Express,TRK978240041,2024-06-22,0,App

In [5]:
customers = pd.read_csv("../Cleaned Data/customers_cleaned.csv")

In [6]:
customers.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,30-07-2024,10-04-2025,0,1,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,05-07-2023,03-05-2024,1,1,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,14-05-2022,31-10-2023,1,1,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,21-01-2025,22-05-2025,1,0,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,06-06-2023,29-03-2024,1,0,4,239808.60

In [7]:
order_items = pd.read_csv("../Cleaned Data/order_items_cleaned.csv")

In [8]:
order_items.head()

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
0,ITM0000001,ORD000001,PRD0522,HCL Cricket Bat Ultra,Sports & Fitness,1,40989,12,4918.68,7861.45,38046.23
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
2,ITM0000003,ORD000001,PRD0613,Voltas Educational Toy Standard,Toys & Baby,1,1585,12,190.20,251.89,1523.31
3,ITM0000004,ORD000002,PRD0556,Ambrane Cycle Standard,Sports & Fitness,3,1107,12,398.52,631.44,3088.08
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93

In [9]:
inventory = pd.read_csv("../Cleaned Data/inventory_cleaned.csv")

In [10]:
inventory.head()

,inventory_id,product_id,warehouse_location,quantity_available,quantity_reserved,reorder_level,reorder_quantity,last_restocked_date,unit_cost,total_inventory_value,status
0,INV0001,PRD0001,Hyderabad-WH4,13,4,49,245,11-09-2023,55738,724594,Low Stock
1,INV0002,PRD0002,Kolkata-WH6,368,14,50,250,10-03-2025,48052,17683136,In Stock
2,INV0003,PRD0003,Delhi-WH2,196,19,44,220,22-11-2024,68913,13506948,In Stock
3,INV0004,PRD0004,Delhi-WH2,432,10,19,57,10-11-2024,80055,34583760,In Stock
4,INV0005,PRD0005,Bengaluru-WH3,404,16,44,88,05-08-2024,8398,3392792,In Stock

In [11]:
products = pd.read_csv("../Cleaned Data/products_cleaned.csv")

In [12]:
products.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,2025-01-29
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,2024-05-17
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,2024-12-28
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,2023-05-04
4,PRD0005,HDFC Smartphone Elite,Electronics,Smartphone,HDFC,SKU-ELE-00005,18715,16226,8398,18,4729,1000,SUP0088,3.9,3700,1,2023-11-27

In [13]:
payments = pd.read_csv("../Cleaned Data/payments_cleaned.csv")

In [14]:
payments.head()

,payment_id,order_id,customer_id,payment_date,payment_time,payment_method,amount,status,transaction_id,bank_name,gateway,refund_amount,refund_date
0,PAY000001,ORD000001,CUST02946,22-05-2025,17:10:00,Cash on Delivery,100984.19,Success,TXN5110698474,SBI,Google Pay,0,NaN
1,PAY000002,ORD000002,CUST04232,16-10-2023,05:32:00,UPI,254478.01,Success,TXN4067460377,IndusInd,Google Pay,0,NaN
2,PAY000003,ORD000003,CUST08078,08-10-2023,12:32:00,Debit Card,32557.06,Success,TXN7056710694,Axis Bank,PhonePe,0,NaN
3,PAY000004,ORD000004,CUST09612,02-10-2023,08:05:00,UPI,24836.94,Success,TXN7460208257,Axis Bank,PhonePe,0,NaN
4,PAY000005,ORD000005,CUST03065,15-06-2024,20:19:00,UPI,156689.29,Success,TXN5835043807,PNB,Razorpay,0,NaN

In [15]:
returns = pd.read_csv("../Cleaned Data/returns_cleaned.csv")

In [16]:
returns.head()

,return_id,order_id,customer_id,return_date,reason,return_amount,refund_status,refund_date,return_condition,remarks
0,RET00001,ORD000015,CUST05470,2024-12-23,Size Issue,24167.33,Pending,2024-12-30,Damaged,Customer initiated return within 7 day window
1,RET00002,ORD000017,CUST07581,2023-11-01,Defective Product,11698.27,Refunded,2023-11-06,Damaged,Customer initiated return within 7 day window
2,RET00003,ORD000038,CUST05691,2025-05-01,Wrong Product Delivered,11147.74,Refunded,2025-05-06,Damaged,Customer initiated return within 7 day window
3,RET00004,ORD000054,CUST03170,2025-06-20,Duplicate Order,9284.55,Refunded,2025-06-24,Acceptable,Customer initiated return within 7 day window
4,RET00005,ORD000072,CUST09318,2025-03-16,Duplicate Order,36912.59,Refunded,2025-03-23,Good,Customer initiated return within 7 day window

KPI1: Gross Merchandise Value (GMV)

In [17]:
gmv = orders["final_amount"].sum()
print("Gross Merchandise Value for all Status:", gmv)

Gross Merchandise Value for all Status: 3147385544.58

Business meaning: This represents the total value of orders in the dataset, including orders that may not have been delivered.

KPI2: Net Revenue

In [18]:
net_revenue = orders.loc[orders["status"] == "Delivered","final_amount"].sum()
print("Net Revenue:",round(net_revenue,2))

Net Revenue: 2053858611.96

Business meaning: This shows the value associated with completed deliveries and helps distinguish delivered business from other order statuses.

KPI3: Average Order Value (AOV)

In [19]:
delivered_orders = orders.loc[orders["status"] == "Delivered", "order_id"].count()


aov = net_revenue/delivered_orders

print("Delivered Orders:", delivered_orders)
print("Average Order Value:",round(aov,2))

Delivered Orders: 32499
Average Order Value: 63197.59

Business Insight: AOV indicates the average revenue generated per delivered order. Monitoring AOV helps the business understand customer spending patterns and identify opportunities to increase order value through product bundling, cross-selling, and targeted promotions.

KPI4: Cancellation Rate

In [20]:
total_orders = orders["order_id"].count()
cancelled_orders = orders.loc[orders["status"] == "Cancelled","order_id"].count()

cancellation_rate = (cancelled_orders/total_orders) * 100

print("Total Orders:",total_orders)
print("Cancelled Orders:",cancelled_orders)
print("Cancellation Rate:",round(cancellation_rate),"%")

Total Orders: 50000
Cancelled Orders: 5996
Cancellation Rate: 12 %

Business meaning: Cancelled orders may represent lost sales and wasted operational effort. The main cancellation reasons need to be investigated.

KPI5: Return Rate

In [21]:
return_records = returns["return_id"].count()

return_rate = (return_records/delivered_orders) * 100

print("Total Return Records:",return_records)
print("Return Rate:",round(return_rate),"%")

Total Return Records: 10000
Return Rate: 31 %

Business meaning: Returns may increase reverse-shipping and processing costs and affect customer satisfaction. The final rate and product-level causes should be verified before submission.

KPI6: Customer Lifetime Value (CLV)

In [22]:
clv = customers.groupby("segment")["total_spent"].mean()
print("Customer Lifetime Value:",round(clv,2))

Customer Lifetime Value: segment
Budget      186178.81
Inactive     32249.08
New         274866.48
Premium     532735.00
Regular     361870.72
Name: total_spent, dtype: float64

Business meaning: Premium customers may be a valuable segment to retain. Further analysis of repeat purchases and profit would provide a fuller picture of customer value.

KPI7: Month-over-Month Growth

In [41]:
orders["order_date"] = pd.to_datetime(orders["order_date"])

orders["month"] = orders["order_date"].dt.to_period("M")

monthly_gmv = orders.groupby("month")["final_amount"].sum()

print(monthly_gmv)

month
2023-06    2.738485e+07
2023-07    1.289205e+08
2023-08    1.281220e+08
2023-09    1.374625e+08
2023-10    1.324709e+08
2023-11    1.372634e+08
2023-12    1.369234e+08
2024-01    1.314500e+08
2024-02    1.209459e+08
2024-03    1.336701e+08
2024-04    1.315097e+08
2024-05    1.363584e+08
2024-06    1.237410e+08
2024-07    1.270283e+08
2024-08    1.319235e+08
2024-09    1.305253e+08
2024-10    1.335183e+08
2024-11    1.262641e+08
2024-12    1.330895e+08
2025-01    1.379291e+08
2025-02    1.141167e+08
2025-03    1.364932e+08
2025-04    1.308222e+08
2025-05    1.358494e+08
2025-06    1.036033e+08
Freq: M, Name: final_amount, dtype: float64

In [42]:
mom_growth = monthly_gmv.pct_change() * 100

print(mom_growth.round(2))

month
2023-06       NaN
2023-07    370.77
2023-08     -0.62
2023-09      7.29
2023-10     -3.63
2023-11      3.62
2023-12     -0.25
2024-01     -4.00
2024-02     -7.99
2024-03     10.52
2024-04     -1.62
2024-05      3.69
2024-06     -9.25
2024-07      2.66
2024-08      3.85
2024-09     -1.06
2024-10      2.29
2024-11     -5.43
2024-12      5.41
2025-01      3.64
2025-02    -17.26
2025-03     19.61
2025-04     -4.15
2025-05      3.84
2025-06    -23.74
Freq: M, Name: final_amount, dtype: float64

Business Insight: Month-over-month GMV fluctuates throughout the period, with a sharp increase of 370.77% in July 2023 and the largest decline of 23.74% in June 2025. The business should investigate the reasons behind these changes and use monthly sales trends to improve demand forecasting, marketing campaigns, and inventory planning.

Year-over-Year Growth

In [43]:
orders["year"] = orders["order_date"].dt.year

yearly_gmv = orders.groupby("year")["final_amount"].sum()

print(yearly_gmv)

year
2023    8.285475e+08
2024    1.560024e+09
2025    7.588141e+08
Name: final_amount, dtype: float64

In [44]:
yoy_growth = yearly_gmv.pct_change() * 100

print(yoy_growth.round(2))

year
2023      NaN
2024    88.28
2025   -51.36
Name: final_amount, dtype: float64

Business Insight: GMV grew by 88.28% in 2024, indicating strong business growth, but declined by 51.36% in 2025. The business should investigate the reasons for the decline and review sales trends, order volume, and customer demand to identify corrective actions. First, confirm whether 2025 data covers the full year.

KPI8: Top Category Revenue Share

In [24]:
category_revenue = order_items.groupby("category")["total_price"].sum()
total_revenue = category_revenue.sum()

revenue_share = (category_revenue / total_revenue) * 100

print("Category Revenue",category_revenue)
print("Revenue Share",revenue_share.round(2),)

Category Revenue category
Automotive          1.234851e+08
Beauty & Health     3.301811e+07
Books               1.394589e+07
Electronics         1.642423e+09
Fashion             1.481553e+08
Grocery             1.871868e+07
Home & Kitchen      2.442952e+08
Office Supplies     9.302935e+07
Sports & Fitness    4.972384e+08
Toys & Baby         4.658385e+07
Name: total_price, dtype: float64
Revenue Share category
Automotive           4.32
Beauty & Health      1.15
Books                0.49
Electronics         57.41
Fashion              5.18
Grocery              0.65
Home & Kitchen       8.54
Office Supplies      3.25
Sports & Fitness    17.38
Toys & Baby          1.63
Name: total_price, dtype: float64

Business meaning: Electronics is a major revenue driver, but its large share creates some dependence on one category. Growing other categories may help diversify revenue.

KPI9: Payment Failure Rate

In [25]:
failed_payments = payments.loc[payments["status"] == "Failed","payment_id"].count()
total_payments = payments["payment_id"].count()

payment_failure_rate = (failed_payments/total_payments) * 100

print("Total Failed Payments",failed_payments)
print("Total Payments",total_payments)
print("Payment Failure Rate",round(payment_failure_rate),"%")

Total Failed Payments 1748
Total Payments 50000
Payment Failure Rate 3 %

Target: Below 2%    
Business meaning: Some customers may be unable to complete their purchases. IndiaKart should investigate failure rates by payment method.

KPI10: Inventory Fill Rate

In [26]:
in_stock_skus = inventory.loc[inventory["quantity_available"] > 0, "product_id"].nunique()

total_skus = products["sku"].nunique()

inventory_fill_rate = (in_stock_skus / total_skus) * 100

print("In-Stock Products:", in_stock_skus)
print("Total SKUs:", total_skus)
print("Inventory Fill Rate:", round(inventory_fill_rate, 2), "%")

In-Stock Products: 998
Total SKUs: 1000
Inventory Fill Rate: 99.8 %

Target > 95%.   
Business meaning: Most tracked products appear to be in stock. IndiaKart should maintain availability while monitoring low-stock products and replenishment needs.

Bonus: Customer Cohort Analysis

In [27]:
print(orders.columns)
print(customers.columns)

Index(['order_id', 'customer_id', 'order_date', 'order_time', 'status', 'city',
       'state', 'pincode', 'total_amount', 'gst_amount', 'shipping_charge',
       'discount_amount', 'final_amount', 'payment_method', 'shipping_partner',
       'tracking_id', 'delivered_date', 'is_cod', 'channel', 'month'],
      dtype='str')
Index(['customer_id', 'first_name', 'last_name', 'email', 'phone', 'city',
       'state', 'pincode', 'gender', 'age', 'segment', 'registration_date',
       'last_login_date', 'is_verified', 'is_active', 'total_orders',
       'total_spent'],
      dtype='str')

In [28]:
customers["registration_date"] = pd.to_datetime(
    customers["registration_date"], dayfirst=True
)

orders["order_date"] = pd.to_datetime(
    orders["order_date"], dayfirst=True
)

In [29]:
customers["cohort_month"] = (
    customers["registration_date"].dt.to_period("M")
)

print(customers[["customer_id", "registration_date", "cohort_month"]].head())

  customer_id registration_date cohort_month
0   CUST00001        2024-07-30      2024-07
1   CUST00002        2023-07-05      2023-07
2   CUST00003        2022-05-14      2022-05
3   CUST00004        2025-01-21      2025-01
4   CUST00005        2023-06-06      2023-06

In [30]:
cohort_customers = customers.groupby("cohort_month")["customer_id"].nunique()

print(cohort_customers)

cohort_month
2020-06     29
2020-07    182
2020-08    193
2020-09    127
2020-10    182
          ...
2025-02    163
2025-03    180
2025-04    159
2025-05    174
2025-06    147
Freq: M, Name: customer_id, Length: 61, dtype: int64

In [34]:
cohort_data = orders.merge(
    customers[["customer_id", "cohort_month"]],
    on="customer_id",
    how="left"
)

print(cohort_data[
    ["customer_id", "cohort_month", "order_date", "order_id"]
].head())

  customer_id cohort_month order_date   order_id
0   CUST02946      2021-01 2025-05-22  ORD000001
1   CUST04232      2021-05 2023-10-16  ORD000002
2   CUST08078      2020-10 2023-10-08  ORD000003
3   CUST09612      2024-01 2023-10-02  ORD000004
4   CUST03065      2024-09 2024-06-15  ORD000005

In [37]:
cohort_data = orders.merge(
    customers[["customer_id", "cohort_month"]],
    on="customer_id",
    how="left"
)

print(cohort_data[
    ["customer_id", "cohort_month", "order_date", "order_id"]
].head())

  customer_id cohort_month order_date   order_id
0   CUST02946      2021-01 2025-05-22  ORD000001
1   CUST04232      2021-05 2023-10-16  ORD000002
2   CUST08078      2020-10 2023-10-08  ORD000003
3   CUST09612      2024-01 2023-10-02  ORD000004
4   CUST03065      2024-09 2024-06-15  ORD000005

In [38]:
cohort_data["order_month"] = (
    cohort_data["order_date"].dt.to_period("M")
)

cohort_data["cohort_index"] = (
    (cohort_data["order_month"].dt.year
     - cohort_data["cohort_month"].dt.year) * 12
    + (cohort_data["order_month"].dt.month
       - cohort_data["cohort_month"].dt.month)
    + 1
)

In [39]:
cohort_data = cohort_data[
    cohort_data["cohort_index"] >= 1
].copy()

print("Valid cohort order records:", len(cohort_data))

Valid cohort order records: 40125

In [40]:
cohort_table = cohort_data[
    cohort_data["cohort_index"].isin([1, 2, 3])
].pivot_table(
    index="cohort_month",
    columns="cohort_index",
    values="order_id",
    aggfunc="nunique",
    fill_value=0
)

cohort_table.columns = ["Month 1", "Month 2", "Month 3"]

print(cohort_table)

              Month 1  Month 2  Month 3
cohort_month
2023-04             0        0        6
2023-05             0        6       37
2023-06             5       32       28
2023-07            34       40       33
2023-08            30       30       36
2023-09            29       40       46
2023-10            36       35       31
2023-11            39       31       30
2023-12            41       23       38
2024-01            32       34       31
2024-02            26       32       36
2024-03            39       37       46
2024-04            33       46       45
2024-05            29       31       28
2024-06            28       34       36
2024-07            39       37       37
2024-08            38       37       40
2024-09            19       32       33
2024-10            29       37       32
2024-11            34       35       31
2024-12            23       39       34
2025-01            39       35       36
2025-02            23       29       33
2025-03            40       42       35
2025-04            40       30       30
2025-05            42       19        0
2025-06            18        0        0

Business meaning: This helps IndiaKart examine how customer activity changes after registration and identify opportunities to encourage repeat purchases.